import { config } from 'dotenv';
import { put } from '@vercel/blob';
import { readdir, readFile } from 'fs/promises';
import { join } from 'path';

// Load environment variables from .env.local
config({ path: '.env.local' });

const DATA_DIR = './public/data';
const BLOB_TOKEN = process.env.BLOB_READ_WRITE_TOKEN;

if (!BLOB_TOKEN) {
  console.error('❌ Error: BLOB_READ_WRITE_TOKEN environment variable not set');
  console.error('Get your token from: https://vercel.com/dashboard/stores');
  process.exit(1);
}

async function uploadFiles() {
  console.log('📁 Reading files from', DATA_DIR);

  const files = await readdir(DATA_DIR);
  const lidarFiles = files.filter(f => f.endsWith('.laz') || f.endsWith('.ply'));

  console.log(`\n📦 Found ${lidarFiles.length} LIDAR files to upload\n`);

  const urlMap = {};

  for (const filename of lidarFiles) {
    const filepath = join(DATA_DIR, filename);
    console.log(`⬆️  Uploading ${filename}...`);

    try {
      const fileContent = await readFile(filepath);
      const blob = await put(filename, fileContent, {
        access: 'public',
        token: BLOB_TOKEN,
      });

      urlMap[filename] = blob.url;
      console.log(`✅ Uploaded: ${blob.url}`);
    } catch (error) {
      console.error(`❌ Failed to upload ${filename}:`, error.message);
    }
  }

  console.log('\n📋 URL Mapping:\n');
  console.log(JSON.stringify(urlMap, null, 2));

  // Save URL map to JSON file
  const { writeFile } = await import('fs/promises');
  await writeFile('./blob-urls.json', JSON.stringify(urlMap, null, 2));
  console.log('\n💾 Saved URL mapping to blob-urls.json');

  // Generate JS config file for the app
  const configContent = `// Auto-generated by upload-to-blob.js
// Do not edit manually - run 'npm run upload-blob' to regenerate

export const BLOB_URLS = ${JSON.stringify(urlMap, null, 2)};

// Helper function to get blob URL or fallback to local path (for dev)
export function getDataUrl(filename) {
  // In production, use Blob URL
  if (BLOB_URLS[filename]) {
    return BLOB_URLS[filename];
  }

  // In development, use local path
  return \`/data/\${filename}\`;
}
`;

  await writeFile('./src/config/blobUrls.js', configContent);
  console.log('💾 Generated src/config/blobUrls.js');
  console.log('\n✅ All done! Your LIDAR files are now hosted on Vercel Blob.');
}

uploadFiles().catch(console.error);
