#!/bin/bash

# Upload LIDAR files to Vercel Blob using Vercel CLI
# This is much faster than the Node.js SDK approach

# Load environment variables
if [ -f .env.local ]; then
  export $(cat .env.local | grep -v '^#' | xargs)
fi

if [ -z "$BLOB_READ_WRITE_TOKEN" ]; then
  echo "❌ Error: BLOB_READ_WRITE_TOKEN not set in .env.local"
  exit 1
fi

echo "📁 Uploading LIDAR files to Vercel Blob..."
echo ""

# Initialize URL map
declare -A url_map

# Count files
file_count=$(find public/data -name "*.laz" -o -name "*.ply" | wc -l | tr -d ' ')
echo "📦 Found $file_count LIDAR files to upload"
echo ""

current=0

# Upload each file
for file in public/data/*.laz public/data/*.ply; do
  if [ -f "$file" ]; then
    filename=$(basename "$file")
    current=$((current + 1))

    echo "[$current/$file_count] ⬆️  Uploading $filename..."

    # Upload using Vercel CLI
    output=$(vercel blob put "$file" --rw-token "$BLOB_READ_WRITE_TOKEN" 2>&1)

    if [ $? -eq 0 ]; then
      # Extract URL from output (format: "Uploaded file to: <url>")
      url=$(echo "$output" | grep -o 'https://[^[:space:]]*')

      if [ -n "$url" ]; then
        echo "✅ Uploaded: $url"
        url_map["$filename"]="$url"
      else
        echo "❌ Failed to extract URL for $filename"
      fi
    else
      echo "❌ Failed to upload $filename: $output"
    fi
  fi
done

echo ""
echo "💾 Generating configuration files..."

# Generate JSON file
cat > blob-urls.json << 'EOF'
{
EOF

first=true
for filename in "${!url_map[@]}"; do
  if [ "$first" = true ]; then
    first=false
  else
    echo "," >> blob-urls.json
  fi
  echo "  \"$filename\": \"${url_map[$filename]}\"" >> blob-urls.json
done

cat >> blob-urls.json << 'EOF'
}
EOF

# Generate JS config file
cat > src/config/blobUrls.js << 'JSEOF'
// Auto-generated by upload-blob-cli.sh
// Do not edit manually - run 'npm run upload-blob' to regenerate

export const BLOB_URLS = {
JSEOF

first=true
for filename in "${!url_map[@]}"; do
  if [ "$first" = true ]; then
    first=false
  else
    echo "," >> src/config/blobUrls.js
  fi
  echo "  \"$filename\": \"${url_map[$filename]}\"" >> src/config/blobUrls.js
done

cat >> src/config/blobUrls.js << 'JSEOF'
};

// Helper function to get blob URL or fallback to local path (for dev)
export function getDataUrl(filename) {
  // In production, use Blob URL
  if (BLOB_URLS[filename]) {
    return BLOB_URLS[filename];
  }

  // In development, use local path
  return `/data/${filename}`;
}
JSEOF

echo "✅ Generated blob-urls.json"
echo "✅ Generated src/config/blobUrls.js"
echo ""
echo "🎉 All done! Your LIDAR files are now hosted on Vercel Blob."
